#!/usr/bin/env python3
"""
Generate internal_users.yml for the Wazuh Indexer with bcrypt hashes.

Called from a .gitlab-ci.yml step. Required env vars:
  - WAZUH_ADMIN_PWD: admin password in plain text (already loaded from wazuh.deploy.env)
  - WAZUH_DASHBOARD_PWD: dashboard user password (same value as INDEXER_PASSWORD
    in the compose file, used for the `kibanaserver` user in OpenSearch)

Output: wazuh.deploy.internal_users.yml in the cwd.

The $2b$ hash prefix is converted to $2y$ for compatibility with the
OpenSearch Security plugin (Java-based). The hash is cryptographically identical
(interoperable); only the prefix differs. Python's bcrypt library outputs $2b$
by default.
"""

import os
import re
import sys
import bcrypt


def convert_bcrypt_prefix(hash_value):
    """Convert $2b$ -> $2y$ for Java OpenSearch compatibility."""
    return re.sub(r'\$2b\$', '$2y$', hash_value, count=1)


def bcrypt_hash(password):
    """Generate a bcrypt hash with a Java-compatible prefix."""
    raw = bcrypt.hashpw(password.encode(), bcrypt.gensalt(rounds=10)).decode()
    return convert_bcrypt_prefix(raw)


def require_env(name):
    """Read an env var, error out if it is missing."""
    value = os.environ.get(name)
    if not value:
        print(f"ERROR: env var {name} not set", file=sys.stderr)
        sys.exit(1)
    return value


admin_pwd = require_env('WAZUH_ADMIN_PWD')
dashboard_pwd = require_env('WAZUH_DASHBOARD_PWD')

admin_hash = bcrypt_hash(admin_pwd)
dashboard_hash = bcrypt_hash(dashboard_pwd)

# Generate the file. Use a plain string (do NOT start with '---' — that is a
# YAML document separator that can confuse a parser when embedded in a heredoc).
content = f'''_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "{admin_hash}"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user (production - hash generated by CI from GitLab variable)"

kibanaserver:
  hash: "{dashboard_hash}"
  reserved: false
  backend_roles: []
  description: "Dashboard user - used by OpenSearch Dashboards to connect to indexer"
'''

with open('wazuh.deploy.internal_users.yml', 'w') as f:
    f.write(content)

print(f"Generated internal_users.yml with admin + kibanaserver users (hash length: {len(admin_hash)})")