#!/usr/bin/env python3
"""Build grafana/dashboards/site-server-overview.json.

Generated by the monitoring session on 2026-09-15. Re-runnable: idempotent.
Reads no files, writes only the dashboard JSON.
"""
import json
import os

dashboard = {
    "title": "site Server Overview",
    "uid": "site-overview",
    "schemaVersion": 39,
    "version": 1,
    "refresh": "30s",
    "time": {"from": "now-6h", "to": "now"},
    "tags": ["site", "proxmox", "node-exporter"],
    "templating": {
        "list": [
            {
                "name": "instance",
                "label": "Instance",
                "type": "query",
                "datasource": "Prometheus",
                "query": 'label_values(node_uname_info{job="site-node-exporter"}, instance)',
                "refresh": 2,
                "includeAll": True,
                "multi": True,
                "allValue": ".+",
                "current": {},
            }
        ]
    },
    "panels": [],
}

# Helper to build a panel dict with consistent schemaVersion 39 fields
def P(pid, title, ptype, x, y, w, h, datasource, targets, **extra):
    p = {
        "id": pid,
        "title": title,
        "type": ptype,
        "gridPos": {"h": h, "w": w, "x": x, "y": y},
        "datasource": datasource,
        "targets": targets,
    }
    p.update(extra)
    return p


def T(expr, legend="{{instance}}", **extra):
    t = {"expr": expr, "legendFormat": legend}
    t.update(extra)
    return t


# TBL() — helper for a table panel. Default: small cells, show header,
# sort by Instance. Multiple targets become columns via refId. Used with
# format=table + instant=true Prometheus queries.
def TBL(pid, title, y, x=0, w=24, h=8, queries=None, transformations=None, **extra):
    p = {
        "id": pid,
        "title": title,
        "type": "table",
        "gridPos": {"h": h, "w": w, "x": x, "y": y},
        "datasource": "Prometheus",
        "targets": queries or [],
        "options": {
            "showHeader": True,
            "cellHeight": "sm",
            "sortBy": [{"displayName": "Instance", "desc": False}],
            "sortDesc": False,
            "wrapHeaderText": False,
        },
        "fieldConfig": {
            "defaults": {"custom": {"align": "auto", "cellOptions": {"type": "auto"}}},
            "overrides": [],
        },
        "transformations": transformations or [],
    }
    p.update(extra)
    return p


# S() — helper for a stat/KPI panel. Default: value+name, area sparkline,
# center justify, threshold-based background color.
def S(pid, title, expr, y, x, w=3, h=4, unit="short",
      text_mode="value_and_name", color_mode="background", graph_mode="area",
      thresholds=None, decimals=None, extra_targets=None, legend="{{instance}}", **extra):
    p = {
        "id": pid,
        "title": title,
        "type": "stat",
        "gridPos": {"h": h, "w": w, "x": x, "y": y},
        "datasource": "Prometheus",
        "targets": [{"expr": expr, "legendFormat": legend}],
        "options": {
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
            "colorMode": color_mode,
            "graphMode": graph_mode,
            "textMode": text_mode,
            "justifyMode": "center",
            "orientation": "auto",
            "textSize": "auto",
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
        },
        "fieldConfig": {
            "defaults": {
                "unit": unit,
                "thresholds": thresholds or {"mode": "absolute", "steps": [
                    {"color": "green", "value": None}]},
                "mappings": [],
                "decimals": decimals,
            },
            "overrides": [],
        },
    }
    if extra_targets:
        p["targets"].extend(extra_targets)
    p.update(extra)
    return p


# G() — gauge panel (speedometer look with needle + threshold zone).
# Default: min=0, max=100, show threshold markers (lines on the gauge),
# orientation horizontal/auto. Difference from S(): G() uses panel type
# "gauge" not "stat", and sets explicit min/max in fieldConfig.
def G(pid, title, expr, y, x, w=3, h=4, unit="percent",
      thresholds=None, decimals=None, legend="{{instance}}",
      min_val=0, max_val=100, **extra):
    p = {
        "id": pid,
        "title": title,
        "type": "gauge",
        "gridPos": {"h": h, "w": w, "x": x, "y": y},
        "datasource": "Prometheus",
        "targets": [{"expr": expr, "legendFormat": legend}],
        "options": {
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
            "showThresholdLabels": False,
            "showThresholdMarkers": True,
            "orientation": "auto",
        },
        "fieldConfig": {
            "defaults": {
                "min": min_val,
                "max": max_val,
                "unit": unit,
                "thresholds": thresholds or {"mode": "absolute", "steps": [
                    {"color": "green", "value": None}]},
                "mappings": [],
                "decimals": decimals,
            },
            "overrides": [],
        },
    }
    p.update(extra)
    return p


dashboard["panels"] = [
    # ── ROW 0: Node Overview ───────────────────────────────────────────────
    # Section headers (id 100/200/300/400) use a Grafana text panel mode=html
    # with an inline background-color for visual separation between sections.
    # The status summary (🟢/🟡/🔴) is hard-coded — a Grafana text panel cannot embed
    # a query result natively. The user sees the section title + status emoji only;
    # the real alert count is already in Panel 32 "Active Alerts" + Panel 18 "Active Alerts".
    P(100, "", "text", 0, 0, 24, 1, None, [],
      options={"mode": "html", "content":
        "<div style='background-color:rgba(33,150,243,0.15); padding:8px 16px; border-left:4px solid #2196f3; height:100%; display:flex; align-items:center;'>"
        "<span style='font-size:18px; font-weight:600;'>🖥️ Node Overview — Proxmox Host &amp; VM</span>"
        "<span style='margin-left:auto; color:#4caf50;'>🟢 Real-time metrics</span></div>"}),

    # ── ROW 1: KPI strip (8 panels) ────────────────────────────────────────
    # 8 panels × w=3 = 24 cols. y=1, h=4 → ends at y=5.
    # Each panel: stat type, sparkline (graphMode=area), threshold-based color.
    S(30, "Hosts UP", "sum(up{job=\"site-node-exporter\"}) / count(up{job=\"site-node-exporter\"}) * 100",
      y=1, x=0, unit="percent",
      legend="UP",
      thresholds={"mode": "absolute", "steps": [
          {"color": "red", "value": None},
          {"color": "yellow", "value": 50},
          {"color": "green", "value": 100}]}),

    S(31, "VMs Running", "sum(pve_up{job=\"site-pve-exporter\", id=~\"qemu/.+\"}) / count(pve_up{job=\"site-pve-exporter\", id=~\"qemu/.+\"}) * 100",
      y=1, x=3, unit="percent",
      legend="RUNNING",
      thresholds={"mode": "absolute", "steps": [
          {"color": "red", "value": None},
          {"color": "yellow", "value": 50},
          {"color": "green", "value": 100}]}),

    S(32, "Active Alerts", "count(ALERTS{alertstate=\"firing\", alertgroup=~\".+site.+|.+site.+\"})",
      y=1, x=6, unit="none",
      legend="FIRING",
      thresholds={"mode": "absolute", "steps": [
          {"color": "green", "value": None},
          {"color": "yellow", "value": 1},
          {"color": "red", "value": 3}]}),

    G(33, "Avg CPU % (all hosts)",
      "100 - (avg(avg by (instance) (rate(node_cpu_seconds_total{job=\"site-node-exporter\", mode=\"idle\"}[5m]))) * 100)",
      y=1, x=9, unit="percent", legend="AVG",
      thresholds={"mode": "absolute", "steps": [
          {"color": "green", "value": None},
          {"color": "yellow", "value": 70},
          {"color": "red", "value": 85}]}),

    G(34, "Avg Memory % (all hosts)",
      "(1 - avg(avg by (instance) (node_memory_MemAvailable_bytes{job=\"site-node-exporter\"} / node_memory_MemTotal_bytes{job=\"site-node-exporter\"}))) * 100",
      y=1, x=12, unit="percent", legend="AVG",
      thresholds={"mode": "absolute", "steps": [
          {"color": "green", "value": None},
          {"color": "yellow", "value": 75},
          {"color": "red", "value": 90}]}),

    G(35, "Top CPU Host", "topk(1, 100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"site-node-exporter\", mode=\"idle\"}[5m])) * 100))",
      y=1, x=15, unit="percent", legend="{{instance}}",
      thresholds={"mode": "absolute", "steps": [
          {"color": "green", "value": None},
          {"color": "yellow", "value": 70},
          {"color": "red", "value": 85}]}),

    G(36, "Top Memory Host", "topk(1, (1 - (node_memory_MemAvailable_bytes{job=\"site-node-exporter\"} / node_memory_MemTotal_bytes{job=\"site-node-exporter\"})) * 100)",
      y=1, x=18, unit="percent", legend="{{instance}}",
      thresholds={"mode": "absolute", "steps": [
          {"color": "green", "value": None},
          {"color": "yellow", "value": 75},
          {"color": "red", "value": 90}]}),

    S(37, "Total Net RX (sum)",
      "sum(rate(node_network_receive_bytes_total{job=\"site-node-exporter\", device!~\"lo|veth.+|docker.+|br-.+\"}[5m]))",
      y=1, x=21, unit="Bps",
      legend="RX",
      graph_mode="area",
      color_mode="value",
      thresholds=None),

    # ── All panels below shifted +4 in y (KPI strip occupies y=1..5) ───────
    # Panel 1 (Instance Up/Down status) REMOVED — replaced by the Host Health Table
    # below (Stage 2). The table sits at y=5..13 (h=8). The CPU/Mem/Disk/Net/Steal/Load panels
    # di-shift +4 dari sebelumnya (y=9..30 jadi y=13..34).
    TBL(50, "🏥 Host Health — all site hosts (pve, Target-1, Target-2)",
      y=5, h=8,
      queries=[
          # A: Status (1=UP, 0=DOWN) — join key: instance
          {"datasource": "Prometheus", "refId": "A", "format": "table", "instant": True,
           "expr": 'up{job="site-node-exporter"}',
           "legendFormat": "Status"},
          # B: CPU % 5m avg
          {"datasource": "Prometheus", "refId": "B", "format": "table", "instant": True,
           "expr": '100 - (avg by (instance) (rate(node_cpu_seconds_total{job="site-node-exporter", mode="idle"}[5m])) * 100)',
           "legendFormat": "CPU %"},
          # C: Memory %
          {"datasource": "Prometheus", "refId": "C", "format": "table", "instant": True,
           "expr": '(1 - (node_memory_MemAvailable_bytes{job="site-node-exporter"} / node_memory_MemTotal_bytes{job="site-node-exporter"})) * 100',
           "legendFormat": "Mem %"},
          # D: Disk / %
          {"datasource": "Prometheus", "refId": "D", "format": "table", "instant": True,
           "expr": '(1 - (node_filesystem_avail_bytes{job="site-node-exporter", mountpoint="/"} / node_filesystem_size_bytes{job="site-node-exporter", mountpoint="/"})) * 100',
           "legendFormat": "Disk / %"},
          # E: Uptime (days since boot)
          {"datasource": "Prometheus", "refId": "E", "format": "table", "instant": True,
           "expr": '(time() - node_boot_time_seconds{job="site-node-exporter"}) / 86400',
           "legendFormat": "Uptime (d)"},
      ],
      transformations=[
                {"id": "merge", "options": {}},
                {"id": "organize", "options": {
                    "excludeByName": {"Time": True},
                    "renameByName": {
                        "Value #A": "Status",
                        "Value #B": "CPU %",
                        "Value #C": "Mem %",
                        "Value #D": "Disk %",
                        "Value #E": "Uptime (d)",
                    },
                }},
            ],
      fieldConfig={"defaults": {"custom": {"align": "auto", "cellOptions": {"type": "auto"}},
                              "unit": "short",
                              "thresholds": {"mode": "absolute", "steps": [
                                  {"color": "green", "value": None},
                                  {"color": "yellow", "value": 70},
                                  {"color": "red", "value": 85}]}}}),

    P(2, "CPU Usage % per Instance", "timeseries", 0, 13, 12, 8, "Prometheus",
      [T('100 - (avg by (instance) (rate(node_cpu_seconds_total{job="site-node-exporter", mode="idle", instance=~"$instance"}[5m])) * 100)')],
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 70}, {"color": "red", "value": 85}]},
          "custom": {"lineWidth": 2, "fillOpacity": 10,
                     "thresholdsStyle": {"mode": "line+area"}}}}),

    P(3, "Memory Usage % per Instance", "timeseries", 12, 13, 12, 8, "Prometheus",
      [T('(1 - (node_memory_MemAvailable_bytes{job="site-node-exporter", instance=~"$instance"} / node_memory_MemTotal_bytes{job="site-node-exporter", instance=~"$instance"})) * 100')],
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 75}, {"color": "red", "value": 90}]},
          "custom": {"lineWidth": 2, "fillOpacity": 10,
                     "thresholdsStyle": {"mode": "line+area"}}}}),

    P(4, "Disk Usage % (/) per Instance", "bargauge", 0, 21, 12, 6, "Prometheus",
      [T('(1 - (node_filesystem_avail_bytes{job="site-node-exporter", mountpoint="/", instance=~"$instance"} / node_filesystem_size_bytes{job="site-node-exporter", mountpoint="/", instance=~"$instance"})) * 100')],
      options={"reduceOptions": {"calcs": ["lastNotNull"]}, "orientation": "horizontal", "displayMode": "gradient"},
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 70}, {"color": "red", "value": 85}]}}}),

    P(5, "Network Traffic per Instance", "timeseries", 12, 21, 12, 6, "Prometheus",
      [T('sum by (instance) (rate(node_network_receive_bytes_total{job="site-node-exporter", device!~"lo|veth.+|docker.+|br-.+", instance=~"$instance"}[5m]))', legend="{{instance}} RX"),
       T('sum by (instance) (rate(node_network_transmit_bytes_total{job="site-node-exporter", device!~"lo|veth.+|docker.+|br-.+", instance=~"$instance"}[5m]))', legend="{{instance}} TX")],
      fieldConfig={"defaults": {"unit": "bytes", "custom": {"lineWidth": 2, "fillOpacity": 8}}}),

    P(6, "CPU Steal & IOWait — Proxmox Host (hypervisor abuse indicator)", "timeseries", 0, 27, 12, 7, "Prometheus",
      [T('avg by (instance) (rate(node_cpu_seconds_total{job="site-node-exporter", mode="steal", instance="192.0.2.2:9100"}[5m])) * 100', legend="Steal — {{instance}}"),
       T('avg by (instance) (rate(node_cpu_seconds_total{job="site-node-exporter", mode="iowait", instance="192.0.2.2:9100"}[5m])) * 100', legend="IOWait — {{instance}}")],
      fieldConfig={"defaults": {"unit": "percent", "min": 0,
          "custom": {"lineWidth": 2, "fillOpacity": 15},
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 5}, {"color": "red", "value": 10}]}}}),

    P(7, "System Load Average per Instance", "timeseries", 12, 27, 12, 7, "Prometheus",
      [T('node_load1{job="site-node-exporter", instance=~"$instance"}', legend="{{instance}} — 1m"),
       T('node_load5{job="site-node-exporter", instance=~"$instance"}', legend="{{instance}} — 5m"),
       T('node_load15{job="site-node-exporter", instance=~"$instance"}', legend="{{instance}} — 15m")],
      fieldConfig={"defaults": {"custom": {"lineWidth": 2}}}),

    # ── ROW 2: Proxmox VE ──────────────────────────────────────────────────
    P(200, "", "text", 0, 34, 24, 1, None, [],
      options={"mode": "html", "content":
        "<div style='background-color:rgba(156,39,176,0.15); padding:8px 16px; border-left:4px solid #9c27b0; height:100%; display:flex; align-items:center;'>"
        "<span style='font-size:18px; font-weight:600;'>🏗️ Proxmox VE — Hypervisor &amp; VM Status</span>"
        "<span style='margin-left:auto; color:#4caf50;'>🟢 VM resource monitoring</span></div>"}),

    # Panel 8 (VM status on Proxmox) REMOVED — replaced by the VM Status Table
    # at y=35..43 (h=8). The VM panels in the section below are shifted +8 cumulatively
    # (4 dari Table 1 + 4 dari Table 2).
    TBL(51, "🏗️ VM Status — all VMs on Proxmox (target-1, target-2)",
      y=35, h=8,
      queries=[
          # A: Status (1=RUNNING, 0=STOPPED) — join key: id
          {"datasource": "Prometheus", "refId": "A", "format": "table", "instant": True,
           "expr": 'pve_up{job="site-pve-exporter", id=~"qemu/.+"}',
           "legendFormat": "{{name}}"},
          # B: CPU %
          {"datasource": "Prometheus", "refId": "B", "format": "table", "instant": True,
           "expr": 'pve_cpu_usage_ratio{job="site-pve-exporter", id=~"qemu/.+"} * 100',
           "legendFormat": "{{name}}"},
          # C: Memory %
          {"datasource": "Prometheus", "refId": "C", "format": "table", "instant": True,
           "expr": '(pve_memory_usage_bytes{job="site-pve-exporter", id=~"qemu/.+"} / pve_memory_size_bytes{job="site-pve-exporter", id=~"qemu/.+"}) * 100',
           "legendFormat": "{{name}}"},
          # D: Net RX rate (B/s)
          {"datasource": "Prometheus", "refId": "D", "format": "table", "instant": True,
           "expr": 'rate(pve_network_receive_bytes_total{job="site-pve-exporter", id=~"qemu/.+"}[5m])',
           "legendFormat": "{{name}}"},
          # E: Net TX rate (B/s)
          {"datasource": "Prometheus", "refId": "E", "format": "table", "instant": True,
           "expr": 'rate(pve_network_transmit_bytes_total{job="site-pve-exporter", id=~"qemu/.+"}[5m])',
           "legendFormat": "{{name}}"},
      ],
      transformations=[
          {"id": "merge", "options": {}},
          {"id": "organize", "options": {
              "excludeByName": {"Time": True},
              "renameByName": {
                  "Value #A": "Status",
                  "Value #B": "CPU %",
                  "Value #C": "Mem %",
                  "Value #D": "RX B/s",
                  "Value #E": "TX B/s",
              },
          }},
      ],
      fieldConfig={"defaults": {"custom": {"align": "auto", "cellOptions": {"type": "auto"}},
                              "unit": "short"}}),
    TBL(52, "🐳 Docker Container Health — all containers on Target-1 & Target-2",
      y=43, h=8,
      queries=[
          # A: Status (1=running, 0=stopped). Join key: container
          {"datasource": "Prometheus", "refId": "A", "format": "table", "instant": True,
           "expr": 'docker_container_up{job="site-node-exporter"}',
           "legendFormat": "{{container}}"},
          # B: Restart count (counter — accumulates since container created)
          {"datasource": "Prometheus", "refId": "B", "format": "table", "instant": True,
           "expr": 'docker_container_restart_count{job="site-node-exporter"}',
           "legendFormat": "{{container}}"},
          # C: Health status (0=none, 1=starting, 2=healthy, 3=unhealthy)
          {"datasource": "Prometheus", "refId": "C", "format": "table", "instant": True,
           "expr": 'docker_container_health_status{job="site-node-exporter"}',
           "legendFormat": "{{container}}"},
      ],
      transformations=[
          {"id": "merge", "options": {}},
          {"id": "organize", "options": {
              "excludeByName": {"Time": True},
              "renameByName": {
                  "Value #A": "Status",
                  "Value #B": "Restarts",
                  "Value #C": "Health",
              },
          }},
      ],
      fieldConfig={"defaults": {"custom": {"align": "auto", "cellOptions": {"type": "auto"}},
                              "unit": "short"}}),
    P(9, "CPU Usage per VM (Proxmox view)", "timeseries", 0, 51, 12, 8, "Prometheus",
      [T('pve_cpu_usage_ratio{job="site-pve-exporter", id=~"qemu/.+"} * 100', legend="{{id}} — {{name}}")],
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 70}, {"color": "red", "value": 85}]},
          "custom": {"lineWidth": 2, "fillOpacity": 10,
                     "thresholdsStyle": {"mode": "line+area"}}}}),

    P(10, "Memory Usage per VM (Proxmox view)", "timeseries", 12, 51, 12, 8, "Prometheus",
      [T('(pve_memory_usage_bytes{job="site-pve-exporter", id=~"qemu/.+"} / pve_memory_size_bytes{job="site-pve-exporter", id=~"qemu/.+"}) * 100', legend="{{id}} — {{name}}")],
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 75}, {"color": "red", "value": 90}]},
          "custom": {"lineWidth": 2, "fillOpacity": 10,
                     "thresholdsStyle": {"mode": "line+area"}}}}),

    P(11, "Disk I/O per VM (Proxmox view)", "timeseries", 0, 59, 12, 7, "Prometheus",
      [T('rate(pve_disk_read_bytes_total{job="site-pve-exporter", id=~"qemu/.+"}[5m])', legend="{{id}} {{name}} — Read"),
       T('rate(pve_disk_write_bytes_total{job="site-pve-exporter", id=~"qemu/.+"}[5m])', legend="{{id}} {{name}} — Write")],
      fieldConfig={"defaults": {"unit": "bytes", "custom": {"lineWidth": 2}}}),

    P(12, "Network I/O per VM (Proxmox view)", "timeseries", 12, 59, 12, 7, "Prometheus",
      [T('rate(pve_network_receive_bytes_total{job="site-pve-exporter", id=~"qemu/.+"}[5m])', legend="{{id}} {{name}} — RX"),
       T('rate(pve_network_transmit_bytes_total{job="site-pve-exporter", id=~"qemu/.+"}[5m])', legend="{{id}} {{name}} — TX")],
      fieldConfig={"defaults": {"unit": "bytes", "custom": {"lineWidth": 2}}}),

    P(13, "Storage Usage Proxmox (local & LVM)", "bargauge", 0, 66, 24, 6, "Prometheus",
      [T('(pve_disk_usage_bytes{job="site-pve-exporter", id=~"storage/.+"} / pve_disk_size_bytes{job="site-pve-exporter", id=~"storage/.+"}) * 100', legend="{{id}}")],
      options={"reduceOptions": {"calcs": ["lastNotNull"]}, "orientation": "horizontal", "displayMode": "gradient"},
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
          "thresholds": {"mode": "absolute", "steps": [
              {"color": "green", "value": 0}, {"color": "yellow", "value": 70}, {"color": "red", "value": 85}]}}}),

    # ── ROW 3: Hypervisor Abuse Detection ─────────────────────────────────────
    P(300, "", "text", 0, 72, 24, 1, None, [],
      options={"mode": "html", "content":
        "<div style='background-color:rgba(244,67,54,0.15); padding:8px 16px; border-left:4px solid #f44336; height:100%; display:flex; align-items:center;'>"
        "<span style='font-size:18px; font-weight:600;'>⚠️ Hypervisor Abuse Detection — CPU &amp; Network Anomaly</span>"
        "<span style='margin-left:auto; color:#4caf50;'>🟢 No anomalies</span></div>"}),

    P(14, "🚨 Sustained CPU > 85% per Instance (5m window)", "timeseries", 0, 73, 12, 8, "Prometheus",
      [T('100 - (avg by (instance) (rate(node_cpu_seconds_total{job="site-node-exporter", mode="idle", instance=~"$instance"}[5m])) * 100)'),
       T("vector(85)", legend="Threshold 85%")],
      fieldConfig={"defaults": {"unit": "percent", "min": 0, "max": 100,
                                "custom": {"lineWidth": 2, "fillOpacity": 15}}}),

    P(15, "CPU Steal Time per Instance (watch > 5%)", "timeseries", 12, 73, 12, 8, "Prometheus",
      [T('avg by (instance) (rate(node_cpu_seconds_total{job="site-node-exporter", mode="steal", instance=~"$instance"}[5m])) * 100', legend="Steal — {{instance}}"),
       T("vector(5)", legend="Threshold 5%")],
      fieldConfig={"defaults": {"unit": "percent", "min": 0,
                                "custom": {"lineWidth": 2, "fillOpacity": 15}}}),

    P(16, "Disk I/O Anomaly per Instance", "timeseries", 0, 81, 12, 7, "Prometheus",
      [T('sum by (instance) (rate(node_disk_read_bytes_total{job="site-node-exporter", instance=~"$instance"}[5m]))', legend="{{instance}} — Read"),
       T('sum by (instance) (rate(node_disk_written_bytes_total{job="site-node-exporter", instance=~"$instance"}[5m]))', legend="{{instance}} — Write")],
      fieldConfig={"defaults": {"unit": "bytes", "custom": {"lineWidth": 2, "fillOpacity": 8}}}),

    P(17, "Outbound Network Anomaly per Instance", "timeseries", 12, 81, 12, 7, "Prometheus",
      [T('sum by (instance) (rate(node_network_transmit_bytes_total{job="site-node-exporter", device!~"lo|veth.+|docker.+|br-.+", instance=~"$instance"}[5m]))', legend="{{instance}} — TX (outbound)")],
      fieldConfig={"defaults": {"unit": "bytes", "custom": {"lineWidth": 2, "fillOpacity": 8}}}),

    # Panel 18 (Active Alerts list) REMOVED — replaced by Panel 54, a state-timeline
    # that is more comprehensive (host up/down + container up/down + alert firing
    # dalam satu timeline horizontal). User lihat SEMUA event di satu tempat
    # for post-incident analysis.
    #
    # Panel 54 — Recent Incidents Timeline (state-timeline panel). Each row
    # is one entity (host/VM/container), value is the state at each timestamp:
    # - up{}: 1 = up (green), 0 = down (red)
    # - docker_container_up{}: 1 = up (green), 0 = down (red)
    # - ALERTS{}: 1 = firing (red), 0 = ok (green)
    # The user can scroll the timeline, see state transitions (e.g. host down at 03:42,
    # back up at 04:15). Default time range is the last 6h.
    P(54, "📅 Recent Incidents — host/VM/container/alert state timeline",
      "state-timeline", 0, 88, 24, 8, "Prometheus",
      # Multiple targets = multiple rows in timeline. RefId A/B/C jadi legend.
      [
        # A: host up — joined by instance label
        {"datasource": "Prometheus", "refId": "A", "instant": True,
         "expr": 'up{job="site-node-exporter"}',
         "legendFormat": "🖥️ {{instance}}"},
        # B: docker container up — joined by host+container
        {"datasource": "Prometheus", "refId": "B", "instant": True,
         "expr": 'docker_container_up{job="site-node-exporter"}',
         "legendFormat": "🐳 {{host}}/{{container}}"},
        # C: alert firing (site alerts) — fires when alertmanager rule is firing
        {"datasource": "Prometheus", "refId": "C", "instant": True,
         "expr": 'count(ALERTS{alertstate="firing", alertgroup=~".+site.+|.+remote.|.+site.+"}) by (alertname)',
         "legendFormat": "🚨 {{alertname}}"},
      ],
      options={
        "showValue": "auto",
        "rowHeight": 0.7,
        "mergeValues": True,
        "legendDisplayMode": "list",
        "tooltipMode": "multi",
        "colorMode": "background",
      },
      fieldConfig={
        "defaults": {
          "custom": {
            "lineWidth": 0,
            "fillOpacity": 80,
            "spanNulls": False,
            "showPoints": "never",
          },
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {"color": "green", "value": None},
              {"color": "red", "value": 1},
            ]
          },
          "mappings": []
        },
        "overrides": []
      }),

    # ── ROW 4: Logs ────────────────────────────────────────────────────────
    P(400, "", "text", 0, 96, 24, 1, None, [],
      options={"mode": "html", "content":
        "<div style='background-color:rgba(33,150,243,0.15); padding:8px 16px; border-left:4px solid #2196f3; height:100%; display:flex; align-items:center;'>"
        "<span style='font-size:18px; font-weight:600;'>📋 Logs — Server site (Loki)</span>"
        "<span style='margin-left:auto; color:#4caf50;'>🟢 Loki connected via NAT</span></div>"}),

    # Panel 19: Auth log — all site hosts (pve, Target-1, Target-2). Promtail on
    # each server scrapes the systemd journal with label job=systemd-journal +
    # host=<hostname>. Filter regex |~ with the (?i) flag for case-insensitivity.
    # IMPORTANT: |= literal match does NOT work for a filter with regex chars
    # (parentheses, pipes) — itu sebabnya filter sebelumnya return 0 streams
    # meskipun ada event "Accepted publickey for root" di journal.
    # Capture: Failed password, Accepted publickey/password, Invalid user,
    # session opened/closed, sudo COMMAND, crypto miner indicators (xmrig,
    # kworker, stratum), dan "user NOT in sudoers".
    P(19, "Auth Log — Login / SSH / sudo Anomalies (all site hosts)", "logs", 0, 97, 24, 10, "LokiSite",
      [T('{job="systemd-journal"} |~ "(?i)(Failed password|Accepted (publickey|password)|Invalid user|session opened|session closed|sudo:.*COMMAND|xmrig|kworker|stratum|mining|user NOT in sudoers)"',
         legend="")],
      options={"showLabels": True, "showTime": True, "wrapLogMessage": True,
               "enableLogDetails": True, "sortOrder": "Descending"}),

    # Panel 20: Application journal on the site VMs only (exclude the Proxmox host 'pve').
    # Promtail's hostname uses $(hostname) substitution in the heredoc, so the
    # host label in Loki is exactly 'Target-1' / 'Target-2' (case-sensitive). Loki's
    # default regex is case-sensitive, so 'target-1|target-2' (lowercase) will NOT match.
    P(20, "Journal — Site applications (Target-1 & Target-2)", "logs", 0, 107, 24, 10, "LokiSite",
      [T('{job="systemd-journal", host=~"Target-1|Target-2"}', legend="")],
      options={"showLabels": True, "showTime": True, "wrapLogMessage": True,
               "enableLogDetails": True, "sortOrder": "Descending"}),

    # Panel 21: Container logs from Docker on the site VMs. Promtail's docker scrape
    # uses job=docker + labels container, compose_project, compose_service.
    # Filter regex |~ with the (?i) flag is case-insensitive to capture
    # error/warn/fail/fatal/panic/exception/traceback. |= literal match also
    # does not work for a regex filter.
    P(21, "Docker Logs — Site applications (Target-1 & Target-2)", "logs", 0, 117, 24, 10, "LokiSite",
      [T('{job="docker", host=~"Target-1|Target-2"} |~ "(?i)(error|warn|fail|fatal|panic|exception|traceback)"',
         legend="")],
      options={"showLabels": True, "showTime": True, "wrapLogMessage": True,
               "enableLogDetails": True, "sortOrder": "Descending"}),

    # Panel 53 (Stage 5): mountpoint disk usage. Previously Panel 4 showed
    # only / (root) — a full /var, /tmp, /opt was NOT visible until
    # disk filling overall. This table exposes EVERY non-virtual mountpoint
    # from all hosts. The regex filter `mountpoint!~"/(sys|proc|dev|host|...)"` excludes
    # virtual filesystems (procfs, sysfs, devtmpfs, etc.) that are not relevant.
    # Useful to catch "/var/log full but / is still 30%" — a silent failure.
    TBL(53, "💾 Mountpoint Disk Usage — all site hosts, all mountpoints",
      y=127, h=8,
      queries=[
          # A: Available bytes (join key: instance+mountpoint). Positive match
          # for real filesystems only (exclude /run, /sys, /proc, /dev, etc.).
          {"datasource": "Prometheus", "refId": "A", "format": "table", "instant": True,
           "expr": 'node_filesystem_avail_bytes{job="site-node-exporter", mountpoint=~"^/($|boot($|/efi)?|home|var($|/log)?|tmp|opt|srv|data|storage)", instance=~"$instance"}',
           "legendFormat": "{{instance}} {{mountpoint}}"},
          # B: Total size bytes
          {"datasource": "Prometheus", "refId": "B", "format": "table", "instant": True,
           "expr": 'node_filesystem_size_bytes{job="site-node-exporter", mountpoint=~"^/($|boot($|/efi)?|home|var($|/log)?|tmp|opt|srv|data|storage)", instance=~"$instance"}',
           "legendFormat": "{{instance}} {{mountpoint}}"},
          # C: Used %
          {"datasource": "Prometheus", "refId": "C", "format": "table", "instant": True,
           "expr": '(1 - node_filesystem_avail_bytes{job="site-node-exporter", mountpoint=~"^/($|boot($|/efi)?|home|var($|/log)?|tmp|opt|srv|data|storage)", instance=~"$instance"} / node_filesystem_size_bytes{job="site-node-exporter", mountpoint=~"^/($|boot($|/efi)?|home|var($|/log)?|tmp|opt|srv|data|storage)", instance=~"$instance"}) * 100',
           "legendFormat": "{{instance}} {{mountpoint}}"},
      ],
      transformations=[
          {"id": "merge", "options": {}},
          {"id": "organize", "options": {
              "excludeByName": {"Time": True},
              "renameByName": {
                  "Value #A": "Available",
                  "Value #B": "Size",
                  "Value #C": "Used %",
              },
          }},
      ],
      fieldConfig={"defaults": {"custom": {"align": "auto", "cellOptions": {"type": "auto"}},
                              "unit": "bytes",
                              "thresholds": {"mode": "absolute", "steps": [
                                  {"color": "green", "value": None},
                                  {"color": "yellow", "value": 70},
                                  {"color": "red", "value": 85}]}}}),
]


# Resolve output path: grafana/dashboards/target-2-monitoring/site-server-overview.json.
# The site dashboards are kept in a separate subdir so Grafana provisioning can load a different
# folder ("Site Monitoring" vs "VPS Monitoring") -- see grafana/provisioning/dashboards/dashboard.yml.
repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_dir = os.path.join(repo_root, "grafana", "dashboards", "target-2-monitoring")
os.makedirs(out_dir, exist_ok=True)
out = os.path.join(out_dir, "site-server-overview.json")

with open(out, "w") as f:
    json.dump(dashboard, f, indent=2)

# Re-load to validate JSON
with open(out) as f:
    loaded = json.load(f)

# Quick sanity
ids = [p["id"] for p in loaded["panels"]]
assert len(ids) == len(set(ids)), f"duplicate panel IDs: {ids}"

print(f"OK  wrote {out}")
print(f"    {os.path.getsize(out)} bytes, {len(loaded['panels'])} panels, uid={loaded['uid']!r}")